openapi: 3.0.3
info:
  title: PostShare Images API
  description: API for uploading and managing images via Cloudinary
  version: 1.0.0
  contact:
    name: PostShare Team

servers:
  - url: https://{domain}/api
    description: Vercel deployment
    variables:
      domain:
        default: localhost:3000
        description: Deployment domain
  - url: http://localhost:3000/api
    description: Local development

tags:
  - name: images
    description: Image upload and management operations

paths:
  /images/upload:
    post:
      tags:
        - images
      summary: Upload image to Cloudinary
      description: |
        Upload an image file to Cloudinary. The image will be automatically compressed,
        optimized, and converted to modern formats (WebP) when possible.
        
        **Note**: This endpoint accepts multipart/form-data with the image file.
        Maximum file size: 5MB. Allowed formats: JPEG, PNG, WebP, GIF.
      operationId: uploadImage
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                  description: Image file to upload
                folder:
                  type: string
                  description: Cloudinary folder (defaults to 'postshare/posts/')
                  default: 'postshare/posts/'
            encoding:
              file:
                contentType: image/jpeg, image/png, image/webp, image/gif
      responses:
        '200':
          description: Image uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageUploadResponse'
        '400':
          description: Invalid file (wrong type, too large, etc.)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                invalidType:
                  value:
                    error: 'Invalid file type. Allowed: JPEG, PNG, WebP, GIF'
                    code: 'INVALID_FILE_TYPE'
                tooLarge:
                  value:
                    error: 'File too large. Maximum size: 5MB'
                    code: 'FILE_TOO_LARGE'
        '413':
          description: Request entity too large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: 'Payload too large'
                code: 'PAYLOAD_TOO_LARGE'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          description: Cloudinary service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: 'Image upload service temporarily unavailable'
                code: 'SERVICE_UNAVAILABLE'

  /images/signed-params:
    get:
      tags:
        - images
      summary: Get signed upload parameters
      description: |
        Generate signed upload parameters for direct browser-to-Cloudinary uploads.
        Returns signature, timestamp, and other parameters needed for secure uploads.
        
        **Use case**: When client wants to upload directly to Cloudinary without
        sending file data through serverless function (avoids payload size limits).
      operationId: getSignedUploadParams
      responses:
        '200':
          description: Signed parameters generated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignedUploadParams'
        '500':
          $ref: '#/components/responses/ServerError'

  /images/{publicId}:
    delete:
      tags:
        - images
      summary: Delete image from Cloudinary
      description: |
        Delete an image from Cloudinary by its public_id.
        Called when a post with an image is deleted, or when replacing an image.
        
        **Note**: The publicId should NOT include the file extension.
        Example: 'postshare/posts/abc123' not 'postshare/posts/abc123.jpg'
      operationId: deleteImage
      parameters:
        - name: publicId
          in: path
          required: true
          description: Cloudinary public_id (without file extension)
          schema:
            type: string
            example: 'postshare/posts/abc123'
          examples:
            standard:
              value: 'postshare/posts/abc123'
              summary: Standard post image
            temp:
              value: 'postshare/temp/xyz789'
              summary: Temporary upload
      responses:
        '200':
          description: Image deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Image deleted successfully'
                  publicId:
                    type: string
                    example: 'postshare/posts/abc123'
                  result:
                    type: string
                    enum: [ok, not found]
                    description: Cloudinary deletion result
        '400':
          description: Invalid public_id format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: 'Invalid public_id format'
                code: 'INVALID_PUBLIC_ID'
        '404':
          description: Image not found in Cloudinary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: 'Image not found'
                code: 'IMAGE_NOT_FOUND'
        '500':
          $ref: '#/components/responses/ServerError'

components:
  schemas:
    ImageUploadResponse:
      type: object
      required:
        - url
        - secureUrl
        - publicId
        - format
        - width
        - height
        - bytes
        - createdAt
      properties:
        url:
          type: string
          format: uri
          description: HTTP URL of uploaded image
          example: 'http://res.cloudinary.com/demo/image/upload/v1234567890/postshare/posts/abc123.jpg'
        secureUrl:
          type: string
          format: uri
          description: HTTPS URL of uploaded image (use this)
          example: 'https://res.cloudinary.com/demo/image/upload/v1234567890/postshare/posts/abc123.jpg'
        publicId:
          type: string
          description: Cloudinary public_id for deletion/transformation
          example: 'postshare/posts/abc123'
        format:
          type: string
          description: Image format after processing
          enum: [jpg, png, webp, gif]
          example: 'jpg'
        width:
          type: integer
          description: Image width in pixels
          example: 1920
        height:
          type: integer
          description: Image height in pixels
          example: 1080
        bytes:
          type: integer
          description: File size in bytes after processing
          example: 245678
        createdAt:
          type: string
          format: date-time
          description: Upload timestamp
          example: '2025-12-25T10:30:00.000Z'
        resourceType:
          type: string
          enum: [image]
          default: image
        type:
          type: string
          description: Upload type
          enum: [upload]
          default: upload
        transformation:
          type: array
          description: Applied transformations (if any)
          items:
            type: object

    SignedUploadParams:
      type: object
      required:
        - signature
        - timestamp
        - cloudName
        - apiKey
        - folder
      properties:
        signature:
          type: string
          description: SHA-1 signature for secure upload
          example: 'a1b2c3d4e5f6g7h8i9j0'
        timestamp:
          type: integer
          description: Unix timestamp (seconds)
          example: 1735123800
        cloudName:
          type: string
          description: Cloudinary cloud name
          example: 'demo'
        apiKey:
          type: string
          description: Cloudinary API key
          example: '123456789012345'
        folder:
          type: string
          description: Destination folder
          default: 'postshare/posts/'
          example: 'postshare/posts/'
        uploadPreset:
          type: string
          description: Cloudinary upload preset (optional)
          example: 'postshare_uploads'
        eager:
          type: string
          description: Eager transformations (optional)
          example: 'w_1920,c_limit,q_auto,f_auto'
        uploadUrl:
          type: string
          format: uri
          description: Full Cloudinary upload URL
          example: 'https://api.cloudinary.com/v1_1/demo/image/upload'

    Error:
      type: object
      required:
        - error
        - code
      properties:
        error:
          type: string
          description: Human-readable error message
        code:
          type: string
          description: Machine-readable error code
        details:
          type: object
          description: Additional error context (optional)

  responses:
    ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            generic:
              value:
                error: 'An unexpected error occurred'
                code: 'INTERNAL_ERROR'
            cloudinary:
              value:
                error: 'Cloudinary upload failed'
                code: 'CLOUDINARY_ERROR'
                details:
                  cloudinaryError: 'Invalid API credentials'

  securitySchemes:
    # Future: Add API key authentication if needed
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key for rate limiting (future enhancement)

# Future security requirement (when rate limiting is added)
# security:
#   - apiKey: []
